name: smartstock
description: SmartStock mobile application
version: 1.4.0-2023.9.2-b.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.7
  crypto: ^3.0.3
  bfast: ^5.0.0-beta.1
  intl: ^0.17.0
  http: ^0.13.5
  tekartik_app_flutter_sembast:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_sembast
      version: '>=0.1.0'
  flutter_svg: ^2.0.7
  workmanager: ^0.5.1
  timeago: ^3.3.0
  charts_flutter: ^0.12.0
  printing: ^5.11.0
  pdf: ^3.10.4
  js: ^0.6.7
  syncfusion_flutter_xlsio: ^20.3.57-beta
  google_mlkit_barcode_scanning: ^0.9.0
  camera: ^0.10.5+4
  image_picker: ^1.0.4
  sembast_sqflite: ^2.2.0
  file_picker: ^5.5.0
  mime: ^1.0.4
  http_parser: ^4.0.2
  url_launcher: ^6.1.14
  geolocator: ^10.1.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
 flutter_test:
   sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
#        - asset: assets/fonts/static/Inter-Black.ttf
#        - asset: assets/fonts/static/Inter-Bold.ttf
#        - asset: assets/fonts/static/Inter-ExtraBold.ttf
#        - asset: assets/fonts/static/Inter-ExtraLight.ttf
#        - asset: assets/fonts/static/Inter-Light.ttf
#        - asset: assets/fonts/static/Inter-Medium.ttf
#        - asset: assets/fonts/static/Inter-Regular.ttf
#        - asset: assets/fonts/static/Inter-SemiBold.ttf
#        - asset: assets/fonts/static/Inter-Thin.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
