name: smartstock
description: SmartStock mobile application
version: 2.0.1-2024.03.01-b.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3
  crypto: ^3.0.3
  intl: ^0.18.0
  http: ^1.1.2
  tekartik_app_flutter_sembast:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_sembast
      version: '>=0.1.0'
  flutter_svg: ^2.0.9
  workmanager: ^0.5.2
  timeago: ^3.6.0
  printing: ^5.11.1
  pdf: ^3.10.7
  js: ^0.6.3
  syncfusion_flutter_xlsio: ^24.1.45
  google_mlkit_barcode_scanning: ^0.10.0
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  sembast_sqflite: ^2.2.0
  file_picker: ^6.1.1
  mime: ^1.0.4
  http_parser: ^4.0.2
  url_launcher: ^6.2.3
  geolocator: ^10.1.0
#  socket_io_client: ^2.0.3+1
  geolocator_web: ^2.2.0
  permission_handler: ^11.1.0

dev_dependencies:
 flutter_test:
   sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-VariableFont_wght.ttf
#        - asset: assets/fonts/static/Inter-Black.ttf
#        - asset: assets/fonts/static/Inter-Bold.ttf
#        - asset: assets/fonts/static/Inter-ExtraBold.ttf
#        - asset: assets/fonts/static/Inter-ExtraLight.ttf
#        - asset: assets/fonts/static/Inter-Light.ttf
#        - asset: assets/fonts/static/Inter-Medium.ttf
#        - asset: assets/fonts/static/Inter-Regular.ttf
#        - asset: assets/fonts/static/Inter-SemiBold.ttf
#        - asset: assets/fonts/static/Inter-Thin.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
