name: smartstock
description: SmartStock mobile application
version: 1.0.0-beta.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.9.0
  bfast: ^3.0.0-beta.3
  #    git:
  #      url: https://github.com/fahamutech/bfast-flutter
  #      ref: 3.x
  bfastui: ^1.0.0-beta.10
#      git:
#        url: https://github.com/fahamutech/bfast-ui-flutter
#        ref: 1.x
  flutter_form_builder: ^3.11.4
  flutter_chips_input: ^1.9.0-dev.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
