name: Publish Web

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
        channel: 'stable'
    - run: curl -sL https://firebase.tools | bash
    - run: flutter pub get
    - run: bash deploy.sh
